### ISSUE TITLE
0.18

### ISSUE THREAD

**Issue by DeadlyKitten37** [Jarcionek/Factorio-Ghost-In-Hand#2]
0.18 has come out, please update this mod so we can use it
Thx

**Comment by Jarcionek** [comment]
Sorry, I don't play Factorio anymore. If you would like to open a pull request with an update, I will be happy to merge it and publish a new version to the mod portal.

**Comment by Jarcionek** [comment]
Updated as suggested in Factorio Mod Portal: https://mods.factorio.com/mod/GhostInHand/discussion/5e3765e94b452d000b2b0e7d
